version: '3.7'

services:
  server:
    #image: seatsurfing/backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      sql:
      http:
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      POSTGRES_URL: 'postgres://seatsurfing:DB_PASSWORD@db/seatsurfing?sslmode=disable'
      JWT_SIGNING_KEY: 'some_random_string'
      BOOKING_UI_BACKEND: 'booking-ui:3001'
      ADMIN_UI_BACKEND: 'admin-ui:3000'
      PUBLIC_URL: 'https://di-seatsurfing.di.fc.ul.pt'
      FRONTEND_URL: 'https://di-seatsurfing.di.fc.ul.pt'
  booking-ui:
    #image: seatsurfing/booking-ui
    build:
      context: .
      dockerfile: Dockerfile.booking-ui
    restart: always
    networks:
      http:
    environment:
      FRONTEND_URL: 'https://di-seatsurfing.di.fc.ul.pt'
  admin-ui:
    #image: seatsurfing/admin-ui:dev
    build:
      context: .
      dockerfile: Dockerfile.admin-ui
    restart: always
    networks:
      http:
    environment:
      FRONTEND_URL: 'https://di-seatsurfing.di.fc.ul.pt'
  db:
    image: postgres:15-alpine
    restart: always
    networks:
      sql:
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: s4rg3nt0!
      POSTGRES_USER: seatsurfing
      POSTGRES_DB: seatsurfing

volumes:
  db:

networks:
  sql:
  http:

